import streamlit as st 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title('Valores historicos de las criptomonedas desde el año 2020 hasta la actualidad')
st.markdown('*****')

bitcoin= pd.read_csv('bitcoinDB.csv')
bnb= pd.read_csv('bnbDB.csv')
car= pd.read_csv('bnbDB.csv')
doge= pd.read_csv('dogecoinDB.csv')
eter= pd.read_csv('ethereumDB.csv')
lido= pd.read_csv('lidoDB.csv')
sol=pd.read_csv('solDB.csv')
teter= pd.read_csv('tetherDB.csv')
usd=pd.read_csv('usdDB.csv')
xrp=pd.read_csv('xrpDB.csv')

st.write('## Precio, capitalizacion de mercado y trading volume')
bitcoin['FECHAS']=pd.to_datetime(bitcoin['FECHAS'])
bnb['FECHAS']=pd.to_datetime(bnb['FECHAS'])
car['FECHAS']=pd.to_datetime(car['FECHAS'])
doge['FECHAS']=pd.to_datetime(doge['FECHAS'])
eter['FECHAS']=pd.to_datetime(eter['FECHAS'])
lido['FECHAS']=pd.to_datetime(lido['FECHAS'])
sol['FECHAS']=pd.to_datetime(sol['FECHAS'])
teter['FECHAS']=pd.to_datetime(teter['FECHAS'])
usd['FECHAS']=pd.to_datetime(usd['FECHAS'])
xrp['FECHAS']=pd.to_datetime(xrp['FECHAS'])

if st.checkbox('BITCOIN'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(bitcoin['FECHAS'], bitcoin['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(bitcoin['FECHAS'], bitcoin['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(bitcoin['FECHAS'], bitcoin['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3)    



if st.checkbox('Ethereum'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(eter['FECHAS'], eter['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(eter['FECHAS'], eter['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(eter['FECHAS'], eter['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('TETHER'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(teter['FECHAS'], teter['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(teter['FECHAS'], teter['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(teter['FECHAS'], teter['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
        
if st.checkbox('BNB'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(bnb['FECHAS'], bnb['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(bnb['FECHAS'], bnb['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(bnb['FECHAS'], bnb['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('XRP'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(xrp['FECHAS'], xrp['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(xrp['FECHAS'], xrp['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(xrp['FECHAS'], xrp['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('USD Coin'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(usd['FECHAS'], usd['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(usd['FECHAS'], usd['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(usd['FECHAS'], usd['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('Lido Staker Ether'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(lido['FECHAS'], lido['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(lido['FECHAS'], lido['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(lido['FECHAS'], lido['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('Cardano'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(car['FECHAS'], car['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(car['FECHAS'], car['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(car['FECHAS'], car['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 

if st.checkbox('Solana'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(sol['FECHAS'], sol['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(sol['FECHAS'], sol['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(sol['FECHAS'], sol['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 
    
if st.checkbox('Doge Coin'):
    fig1= plt.figure(figsize=(10, 6))
    plt.plot(doge['FECHAS'], doge['PRECIO-usd'], label='Precio de Cierre', color='blue')
    plt.xlabel('Fecha')
    plt.ylabel('Precio USD')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig1)
    
    fig2= plt.figure(figsize=(10, 6))
    plt.plot(doge['FECHAS'], doge['MARKET_CAP-usd'], label='market cap', color='red')
    plt.xlabel('Fecha')
    plt.ylabel('Market Cap')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
    fig3= plt.figure(figsize=(10, 6))
    plt.plot(doge['FECHAS'], doge['TOTAL_VOLUMES'], label='volumen', color='orange')
    plt.xlabel('Fecha')
    plt.ylabel('Volume')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig3) 