import streamlit as st 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title('Indice de Fuerza Relativa y Media movil')
st.markdown('*****') 

if st.button('RSI'):
    st.write('El RSI es un indicador de "momentum" que manifiesta si un activo está sobrecomprado o sobrevendido. Lo hace midiendo la magnitud de los cambios de precio recientes (la configuración estándar son los 14 periodos previos –es decir, 14 días). Muestra el ritmo (momentum) al que el precio está cambiando. Esto significa que, si el "momentum" se incrementa mientras el precio sube, la tendencia al alza es fuerte y cada vez más compradores están entrando. Por el contrario, si el "momentum" se reduce mientras el precio sube, podría indicar que pronto los vendedores se harán con el control del mercado. Una interpretación tradicional del RSI dice que por encima de 70 un activo está sobrecomprado, mientras que por debajo de 30 está sobrevendido. ')
if st.button('Media Movil'):
    st.write('Una media móvil suaviza la acción del precio al filtrar el "ruido" del mercado y resaltar la dirección de la tendencia. Dado que se basa en datos del precio pasados, se considera un indicador atrasado. Cuanto más largo sea el periodo, mayor será el atraso. Por lo tanto, la SMA de 200 días reaccionará de forma más lenta a la acción del precio reciente que la SMA de 50 días. Los traders a menudo utilizan la relación del precio con determinadas medias móviles para evaluar la tendencia actual del mercado.')

bitcoin= pd.read_csv('bitcoinDB.csv')
bnb= pd.read_csv('bnbDB.csv')
car= pd.read_csv('bnbDB.csv')
doge= pd.read_csv('dogecoinDB.csv')
eter= pd.read_csv('ethereumDB.csv')
lido= pd.read_csv('lidoDB.csv')
sol=pd.read_csv('solDB.csv')
teter= pd.read_csv('tetherDB.csv')
usd=pd.read_csv('usdDB.csv')
xrp=pd.read_csv('xrpDB.csv')

bitcoin['FECHAS']=pd.to_datetime(bitcoin['FECHAS'])
bnb['FECHAS']=pd.to_datetime(bnb['FECHAS'])
car['FECHAS']=pd.to_datetime(car['FECHAS'])
doge['FECHAS']=pd.to_datetime(doge['FECHAS'])
eter['FECHAS']=pd.to_datetime(eter['FECHAS'])
lido['FECHAS']=pd.to_datetime(lido['FECHAS'])
sol['FECHAS']=pd.to_datetime(sol['FECHAS'])
teter['FECHAS']=pd.to_datetime(teter['FECHAS'])
usd['FECHAS']=pd.to_datetime(usd['FECHAS'])
xrp['FECHAS']=pd.to_datetime(xrp['FECHAS'])

bitcoin2= bitcoin.tail(14)
bnb2=bnb.tail(14)
car2=car.tail(14)
doge2=doge.tail(14)
eter2=eter.tail(14)
lido2=lido.tail(14)
sol2=sol.tail(14)
teter2=teter.tail(14)
usd2=usd.tail(14)
xrp2=xrp.tail(14)

if st.checkbox('BITCOIN'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(bitcoin2['FECHAS'], bitcoin2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(bitcoin2['FECHAS'], bitcoin2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(bitcoin2['FECHAS'], bitcoin2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)

if st.checkbox('ETHEREUM'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(eter2['FECHAS'], eter2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(eter2['FECHAS'], eter2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(eter2['FECHAS'], eter2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
if st.checkbox('Tether usd'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(teter2['FECHAS'], teter2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(teter2['FECHAS'], teter2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(teter2['FECHAS'], teter2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
if st.checkbox('BNB'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(bnb2['FECHAS'], bnb2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(bnb2['FECHAS'], bnb2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(bnb2['FECHAS'], bnb2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
if st.checkbox('XRP'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(xrp2['FECHAS'], xrp2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(xrp2['FECHAS'], xrp2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(xrp2['FECHAS'], xrp2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)

if st.checkbox('USD Coin'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(usd2['FECHAS'], usd2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(usd2['FECHAS'], usd2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(usd2['FECHAS'], usd2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
if st.checkbox('Lido Staker Ether'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(lido2['FECHAS'], lido2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(lido2['FECHAS'], lido2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(lido2['FECHAS'], lido2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)

if st.checkbox('Cardano'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(car2['FECHAS'], car2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(car2['FECHAS'], car2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(car2['FECHAS'], car2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)
    
if st.checkbox('Solana'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(sol2['FECHAS'], sol2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(sol2['FECHAS'], sol2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(sol2['FECHAS'], sol2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)

if st.checkbox('Doge Coin'):
    fig= plt.figure(figsize=(10, 6))
    plt.plot(doge2['FECHAS'], doge2['RSI'], label='RSI')
    plt.axhline(y=70, color='r', linestyle='--', label='Sobrecompra (70)')
    plt.axhline(y=30, color='g', linestyle='--', label='Sobreventa (30)')
    plt.title('Índice de Fuerza Relativa (RSI)')
    plt.xlabel('Fecha')
    plt.ylabel('RSI')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)
    
    fig2=plt.figure(figsize=(10, 6))
    plt.plot(doge2['FECHAS'], doge2['PRECIO-usd'], label='Precio de Cierre')
    plt.plot(doge2['FECHAS'], doge2['MovingAverage'], label=f'Media Móvil (14 días)')
    plt.title('Precio de la Criptomoneda con Media Móvil')
    plt.xlabel('Fecha')
    plt.ylabel('Precio')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig2)